version: "3"
services:

  pg:
    image: postgres:9.6
    restart: always
    #Required env: POSTGRES_USER, POSTGRES_PASSWORD
    env_file: .env
    ports:
      - "5432:5432"

  api:
    image: bn-api
    build: ../bn-api
    depends_on:
          - pg
    env_file: .env
    ports:
      - "$API_PORT:$API_PORT"

  curl:
    image: tutum/curl

